default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: pingcrm_development

test:
  <<: *default
  database: pingcrm_test

production:
  <<: *default
  database: pingcrm_production
